# Generated by Django 4.2.4 on 2023-08-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_articlescategories_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_flag', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.category')),
            ],
            options={
                'verbose_name': 'Тематика статьи',
                'verbose_name_plural': 'Тематика статьи',
            },
        ),
        migrations.DeleteModel(
            name='ArticlesCategories',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(through='articles.Scope', to='articles.category'),
        ),
    ]
